-
  branches:
    only:
      - production

  version: 1.1.{build}

  configuration: Release

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  cache:
    - packages

  nuget:
    disable_publish_on_pr: true

  install:
    - nuget restore

  build:
    project: coveralls.net.sln
    verbosity: quiet

  before_deploy:
    - cd coveralls.net\package
    - nuget pack coveralls.net.nuspec -Version "%APPVEYOR_BUILD_VERSION%"
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  deploy:
  - provider: NuGet
    api_key:
      secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61

-
  branches:
    only:
      - master

  version: 1.1.{build}-beta

  configuration: Debug

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  cache:
    - packages

  nuget:
    disable_publish_on_pr: true

  environment:
    COVERALLS_REPO_TOKEN:
      secure: fm7taq4Ao1Fu09OLM+KKQJlLwUsmDq9801njnfwhSTadQ3eAcYx+meW/LxK/4Mq0

  install:
    - nuget restore

  build:
    project: coveralls.net.sln
    verbosity: minimal

  after_test:
    - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[Coveralls*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single Coveralls.Tests\bin\%CONFIGURATION%\Coveralls.Tests.dll" -output:coverage.xml
    - packages\coveralls.io.1.1.60\tools\coveralls.net.exe --opencover coverage.xml

  before_deploy:
    - cd coveralls.net\package
    - nuget pack coveralls.net.nuspec -Version "%APPVEYOR_BUILD_VERSION%"
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  deploy:
  - provider: NuGet
    api_key:
      secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61
